# Generated by Django 5.2.7 on 2025-11-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('ALL', 'All')], db_index=True, default='ALL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_type',
            field=models.CharField(choices=[('GR', 'Gram'), ('PC', 'Peace'), ('L', 'Litre')], default='GR'),
        ),
    ]
